[2022-06-27 17:44:08,614] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: trigger_dag.gridSearchLR 2022-06-27T17:34:37.557225+00:00 [queued]>
[2022-06-27 17:44:08,629] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: trigger_dag.gridSearchLR 2022-06-27T17:34:37.557225+00:00 [queued]>
[2022-06-27 17:44:08,630] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 17:44:08,630] {taskinstance.py:1043} INFO - Starting attempt 2 of 1
[2022-06-27 17:44:08,631] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 17:44:08,647] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): gridSearchLR> on 2022-06-27T17:34:37.557225+00:00
[2022-06-27 17:44:08,653] {standard_task_runner.py:52} INFO - Started process 177 to run task
[2022-06-27 17:44:08,664] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_dag', 'gridSearchLR', '2022-06-27T17:34:37.557225+00:00', '--job-id', '1254', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/tmp/tmplyy_l5pt', '--error-file', '/tmp/tmpbvhkfkoo']
[2022-06-27 17:44:08,667] {standard_task_runner.py:77} INFO - Job 1254: Subtask gridSearchLR
[2022-06-27 17:44:08,723] {logging_mixin.py:104} INFO - Running <TaskInstance: trigger_dag.gridSearchLR 2022-06-27T17:34:37.557225+00:00 [running]> on host 8799fce82f30
[2022-06-27 17:44:08,768] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=trigger_dag
AIRFLOW_CTX_TASK_ID=gridSearchLR
AIRFLOW_CTX_EXECUTION_DATE=2022-06-27T17:34:37.557225+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-27T17:34:37.557225+00:00
[2022-06-27 17:44:08,771] {taskinstance.py:1455} ERROR - [Errno 13] Permission denied: '/Users/administrador/Desktop/airflow-docker-main/mlruns/.trash'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/trigger_dag.py", line 42, in prueba
    client = MlflowClient()
  File "/home/airflow/.local/lib/python3.6/site-packages/mlflow/tracking/client.py", line 70, in __init__
    self._tracking_client = TrackingServiceClient(final_tracking_uri)
  File "/home/airflow/.local/lib/python3.6/site-packages/mlflow/tracking/_tracking_service/client.py", line 48, in __init__
    self.store
  File "/home/airflow/.local/lib/python3.6/site-packages/mlflow/tracking/_tracking_service/client.py", line 52, in store
    return utils._get_store(self.tracking_uri)
  File "/home/airflow/.local/lib/python3.6/site-packages/mlflow/tracking/_tracking_service/utils.py", line 155, in _get_store
    return _tracking_store_registry.get_store(store_uri, artifact_uri)
  File "/home/airflow/.local/lib/python3.6/site-packages/mlflow/tracking/_tracking_service/registry.py", line 39, in get_store
    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
  File "/home/airflow/.local/lib/python3.6/site-packages/mlflow/tracking/_tracking_service/registry.py", line 49, in _get_store_with_resolved_uri
    return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
  File "/home/airflow/.local/lib/python3.6/site-packages/mlflow/tracking/_tracking_service/utils.py", line 109, in _get_file_store
    return FileStore(store_uri, store_uri)
  File "/home/airflow/.local/lib/python3.6/site-packages/mlflow/store/tracking/file_store.py", line 149, in __init__
    mkdir(self.trash_folder)
  File "/home/airflow/.local/lib/python3.6/site-packages/mlflow/utils/file_utils.py", line 114, in mkdir
    raise e
  File "/home/airflow/.local/lib/python3.6/site-packages/mlflow/utils/file_utils.py", line 111, in mkdir
    os.makedirs(target)
  File "/usr/local/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/administrador/Desktop/airflow-docker-main/mlruns/.trash'
[2022-06-27 17:44:08,777] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=trigger_dag, task_id=gridSearchLR, execution_date=20220627T173437, start_date=20220627T174408, end_date=20220627T174408
[2022-06-27 17:44:08,834] {local_task_job.py:146} INFO - Task exited with return code 1
