[2022-06-27 11:11:33,309] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: trigger_dag.gridSearchLR 2022-06-27T11:11:31.744643+00:00 [queued]>
[2022-06-27 11:11:33,322] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: trigger_dag.gridSearchLR 2022-06-27T11:11:31.744643+00:00 [queued]>
[2022-06-27 11:11:33,323] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 11:11:33,324] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-06-27 11:11:33,324] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 11:11:33,331] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): gridSearchLR> on 2022-06-27T11:11:31.744643+00:00
[2022-06-27 11:11:33,337] {standard_task_runner.py:52} INFO - Started process 228 to run task
[2022-06-27 11:11:33,341] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_dag', 'gridSearchLR', '2022-06-27T11:11:31.744643+00:00', '--job-id', '625', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/tmp/tmpnc9nhfvh', '--error-file', '/tmp/tmpkqk3s6qt']
[2022-06-27 11:11:33,344] {standard_task_runner.py:77} INFO - Job 625: Subtask gridSearchLR
[2022-06-27 11:11:33,388] {logging_mixin.py:104} INFO - Running <TaskInstance: trigger_dag.gridSearchLR 2022-06-27T11:11:31.744643+00:00 [running]> on host 61d9f46d7859
[2022-06-27 11:11:33,426] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=trigger_dag
AIRFLOW_CTX_TASK_ID=gridSearchLR
AIRFLOW_CTX_EXECUTION_DATE=2022-06-27T11:11:31.744643+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-27T11:11:31.744643+00:00
[2022-06-27 11:11:33,428] {logging_mixin.py:104} INFO - file:///opt/airflow/mlruns
[2022-06-27 11:11:37,374] {logging_mixin.py:104} WARNING - 2022/06/27 11:11:37 WARNING mlflow.tracking.context.git_context: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2022-06-27 11:11:37,375] {logging_mixin.py:104} WARNING - 
[2022-06-27 11:11:37,488] {logging_mixin.py:104} INFO - newton-cg 0.0001
[2022-06-27 11:11:41,269] {python.py:118} INFO - Done. Returned value was: None
[2022-06-27 11:11:41,284] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=trigger_dag, task_id=gridSearchLR, execution_date=20220627T111131, start_date=20220627T111133, end_date=20220627T111141
[2022-06-27 11:11:41,312] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-06-27 11:11:41,356] {local_task_job.py:146} INFO - Task exited with return code 0
